noisy_label2id={
    'normal' : 0, 
    'noisy' : 1
}

noisy_id2label={
    0 : 'normal', 
    1 : 'noisy'
}

entities = ["GIA",
            "DIA_CHI",
            "DIEN_TICH",
            "VI_TRI",
            "DUONG_TRUOC_NHA",
            "BIEN",
            "SONG",
            "PHONG_NGU",
            "TOILET",
            "SO_TANG",
            "DICH_VU",
            "KICH_THUOC"]

ner_label2id = {'O' : 0,
                'B-BIEN': 1,
                'B-DIA_CHI': 2,
                'B-DICH_VU': 3,
                'B-DIEN_TICH': 4,
                'B-DUONG_TRUOC_NHA': 5,
                'B-GIA': 6,
                'B-KICH_THUOC': 7,
                'B-PHONG_NGU': 8,
                'B-SONG': 9,
                'B-SO_TANG': 10,
                'B-TOILET': 11,
                'B-VI_TRI': 12,
                'I-BIEN': 13,
                'I-DIA_CHI': 14,
                'I-DICH_VU': 15,
                'I-DIEN_TICH': 16,
                'I-DUONG_TRUOC_NHA': 17,
                'I-GIA': 18,
                'I-KICH_THUOC': 19,
                'I-PHONG_NGU': 20,
                'I-SONG': 21,
                'I-SO_TANG': 22,
                'I-TOILET': 23,
                'I-VI_TRI': 24,
                }

ner_id2label = {0 : 'O',
                1: 'B-BIEN',
                2: 'B-DIA_CHI',
                3: 'B-DICH_VU',
                4: 'B-DIEN_TICH',
                5: 'B-DUONG_TRUOC_NHA',
                6: 'B-GIA',
                7: 'B-KICH_THUOC',
                8: 'B-PHONG_NGU',
                9: 'B-SONG',
                10: 'B-SO_TANG',
                11: 'B-TOILET',
                12: 'B-VI_TRI',
                13: 'I-BIEN',
                14: 'I-DIA_CHI',
                15: 'I-DICH_VU',
                16: 'I-DIEN_TICH',
                17: 'I-DUONG_TRUOC_NHA',
                18: 'I-GIA',
                19: 'I-KICH_THUOC',
                20: 'I-PHONG_NGU',
                21: 'I-SONG',
                22: 'I-SO_TANG',
                23: 'I-TOILET',
                24: 'I-VI_TRI',
                }